sonata_admin:
    title: 'Library Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            admin:
                label: Administrador
                icon: <i class='fa fa-pencil'></i>
            cache:
                label: Herramientas
                icon: <i class='fa fa-gears'></i>
                items:
                    - route: admin_cache_clear
                      label: Limpiar caché
    global_search:
        empty_boxes: hide
        admin_route: edit

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
